on:
  pull_request:
    branches: [ main ]

jobs:
  check_formula:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-latest, ubuntu-latest]

    steps:
    - name: Checkout Tap
      uses: actions/checkout@v4

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Check Formula Style
      run: |
        brew style Formula/cb.rb

    # TODO (abrightwell): remove this is favor of the below when release
    # repo is made public.
    - name: Audit Formula
      run: brew audit --strict cb

    # - name: Audit Formula
    #   run: brew audit --strict --online cb
    #
    # - name: Tap and Install Formula
    #   run: |
    #     brew tap "$GITHUB_REPOSITORY"
    #     brew install cb

    # - name: Test Formula
    #   run: |
    #     cb version
