name: brew pr-pull
on:
  pull_request_target:
    types:
      - labeled
  workflow_dispatch:

jobs:
  pr-pull:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: macos-latest
    steps:
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Update Homebrew
        run: brew update

      - name: Set up git
        run: |
          git config --global user.name "Bridge CI Bot"
          git config --global user.email "bridge-bot@crunchydata.com"

      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
          PULL_REQUEST: ${{ github.event.pull_request.number }}
        run: |
          brew pr-pull \
          --artifact-pattern=bottle-* \
          --tap=$GITHUB_REPOSITORY \
          --workflows=ci.yml \
          --no-upload \
          --debug \
          --verbose \
          --dry-run \
          $PULL_REQUEST

      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
        with:
          token: ${{ github.token }}
          branch: main

      - name: Delete branch
        if: github.event.pull_request.head.repo.fork == false
        env:
          BRANCH: ${{ github.event.pull_request.head.ref }}
        run: git push --delete origin $BRANCH